FountainHub/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('news/', include('news.urls')),
    path('event/', include('event.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='index'),

    # CATEGORIES LINKS - Shows posts by categories
    # Shows all posts under campus
    path('campus/', views.campus_post, name='campus'),
    path('career/', views.career_post, name='career'),
    path('interview/', views.interview_post, name='interview'),
    path('others/', views.others_post, name='others'),
    path('islam/', views.islam_post, name='islam'),
    path('tutorial/', views.tutorial_post, name='tutorial'),

    # Full url would be something like; domainname.com/blog/add
    path('add/', views.add_post, name='add_post'),


    path('<slug:slug>/edit/', views.edit_post, name='edit_post'),

    path('<slug:slug>/delete/', views.PostDelete.as_view(), name='post-delete'),

    path('<slug:slug>/login/', views.post_login, name='post_login'),

    path('<slug:slug>/like/', views.like_post, name='like_post'),

    path('<slug:slug>/', views.post_detail, name='details'),






    #path('archive/<int:year>/<str:month>/', views.EventMonthArchiveView.as_view(), name="archive_month"),

    #path('archive/<int:year>/', views.EventYearArchiveView.as_view(), name="article_year_archive"),
]

event/urls.py
from django.urls import path
from . import views


app_name = 'event'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),

    path('archive/<int:year>/<str:month>/', views.EventMonthArchiveView.as_view(), name="archive_month"),

    path('archive/<int:year>/', views.EventYearArchiveView.as_view(), name="article_year_archive"),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.index, name='index')
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('add/', views.add_post, name='add_post'),

    path('<slug:slug>/edit/', views.edit_post, name='edit_post'),

    path('<slug:slug>/login/', views.post_login, name='post_login'),

    path('<slug:slug>/delete/', views.PostDelete.as_view(), name='post-delete'),

    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),

    path('archive/<int:year>/<str:month>/', views.ArticleMonthArchiveView.as_view(), name="archive_month"),

    path('archive/<int:year>/', views.ArticleYearArchiveView.as_view(), name="article_year_archive"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
import random
from news.models import Article
from blog.models import Post
from event.models import Event
from django.http import HttpResponse
from django.db.models import Count

def index(request):
	first_career = Article.objects.order_by('-pub_date')[:1]
	article_list = Article.objects.order_by('-pub_date')[1:5]
	event_list = Event.objects.order_by('-start_date')[:4]
	popular_posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-num_likes')[:5]
	

	context = {
        'article_list': article_list,
        'first_career': first_career,
        'event_list': event_list,
        'popular_posts': popular_posts,
        }



	return render(request, 'home/index.html', context)

home/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block header %}

<div class="header-div">
    <h1>Home</h1>
</div>

{% endblock %}

{% block content %}
<div class="container-fluid">

<!-- Latest News -->
<div class="campus_list" style="float: none;">
    <div class="popular-posts">
        <div class="title">
            <h2><span class="gap"></span>Latest News</h2>
            <span class="title-span"></span>
        </div>
    </div>
    <div class="widget-content">
        <div class="row">
            <div class="col-md-6">
                {% for article in first_career %}
                    <div class="bx-first">
                        <div class="bx-item">
                            <div class="box-thumbnail">
                                <a href="{% url 'news:detail' article.slug %}">
                                    <img src="{{ article.picture.url }}">
                                </a>
                            </div>
                            <div class="bf-content">
                                <h3 class="recent-title">
                                    <a href="{% url 'news:detail' article.slug %}">{{article.headline}}</a>
                                </h3>
                                <span class="recent-date">{{article.pub_date}} - {{article.author}}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-6">
                <ul>
                    {% for article in article_list %}
                        <li>
                           <div class="box-thumbnail">
                               <a href="{% url 'news:detail' article.slug %}">
                                    <img src="{{ article.picture.url }}" width="90" height="70">
                                </a>
                           </div>
                           <div class="recent-content">
                               <h3 class="recent-title">
                                    <a href="{% url 'news:detail' article.slug %}">{{article.headline}}</a>
                                </h3>
                               <span class="recent-date">{{article.pub_date}} - {{article.author}}</span>
                           </div>
                           <div class="clear"></div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End of Latest News-->

<!-- Events -->
<div class="popular-posts">
    <div class="title">
        <h2><span class="gap"></span>Upcoming Events</h2>
        <span class="title-span"></span>
    </div>
</div>
<div class="card-deck">
    {% for event in event_list %}
        <div class="card text-center" style="border: none;">
                <img class="card-img-top" src="{{ event.thumbnail.url }}" alt="{{event.title}}" style="height: 250px;">
            <div class="card-body">
                <h2 class="post-title">{{event.title}}</h2>
                <span class="recent-date">{{event.start_date}} - {{event.organizer}}</span>
                <br>
                <a class="read-more" href="{% url 'event:detail' event.slug %}">Read More</a>
            </div>
        </div>
    {% endfor %}
</div>
<!-- End of Events-->

<!-- Random Posts-->
<div class="popular-posts">
    <div class="title" style="margin-left: 15px;">
        <h2><span class="gap"></span>Popular Posts</h2>
        <span class="title-span"></span>
    </div>
	{% for post in popular_posts %}
		<div class="recent-posts">
            <div class="post-outer">
                <div class="post">
                    <div class="container-fluid">
                    <div class="row">
                            <div  class="col-md-5">
                                <div class="block-image">
                                    <div class="thumb">
                                        <a href="{% url 'blog:details' post.slug %}">
                                            <img src="{{ post.thumbnail.url }}">
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="post-header">
                                </div>
                                <article>
                                    <font class="retitle">
                                        <h2>
                                            <a href="{% url 'blog:details' post.slug %}"> {{post.title}}</a>
                                        </h2>
                                    </font>
                                    <div class="date-header">
                                        <div id="meta-post">
                                            <p>{{ post.published_date }} - {{post.author}} </p>
                                        </div>
                                        <div class="resumo">
                                            <span>{{ post.text| truncatewords:20 |safe }}</span>
                                            <br>
                                            <a class="read-more" href="{% url 'blog:details' post.slug %}">Read More</a>
                                        </div>
                                        <div style="clear: both;"></div>
                                    </div>
                                </article>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div> 
	{% endfor %}
</div>
<!-- End of Random Posts-->

</div>
{% endblock %}