FountainHub/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('news/', include('news.urls')),
    path('event/', include('event.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='index'),

    # CATEGORIES LINKS - Shows posts by categories
    # Shows all posts under campus
    path('campus/', views.campus_post, name='campus'),
    path('career/', views.career_post, name='career'),
    path('interview/', views.interview_post, name='interview'),
    path('others/', views.others_post, name='others'),
    path('islam/', views.islam_post, name='islam'),
    path('tutorial/', views.tutorial_post, name='tutorial'),

    # Full url would be something like; domainname.com/blog/add
    path('add/', views.add_post, name='add_post'),


    path('<slug:slug>/edit/', views.edit_post, name='edit_post'),

    path('<slug:slug>/delete/', views.PostDelete.as_view(), name='post-delete'),

    path('<slug:slug>/login/', views.post_login, name='post_login'),

    path('<slug:slug>/like/', views.like_post, name='like_post'),

    path('<slug:slug>/', views.post_detail, name='details'),






    #path('archive/<int:year>/<str:month>/', views.EventMonthArchiveView.as_view(), name="archive_month"),

    #path('archive/<int:year>/', views.EventYearArchiveView.as_view(), name="article_year_archive"),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('add/', views.add_post, name='add_post'),

    path('<slug:slug>/edit/', views.edit_post, name='edit_post'),

    path('<slug:slug>/login/', views.post_login, name='post_login'),

    path('<slug:slug>/delete/', views.PostDelete.as_view(), name='post-delete'),

    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),

    path('archive/<int:year>/<str:month>/', views.ArticleMonthArchiveView.as_view(), name="archive_month"),

    path('archive/<int:year>/', views.ArticleYearArchiveView.as_view(), name="article_year_archive"),
]

news/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.urls import reverse


class Article(models.Model):
    reporter = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now=True)
    picture = models.ImageField(blank=True)
    headline = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(default='', blank=True, unique=True)
    content = RichTextUploadingField()

    class Meta:
        ordering = ['-pub_date']

    def save(self):
        self.slug = slugify(self.headline)
        super(Article, self).save()

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        return reverse('news:detail', kwargs={'slug': self.slug})


class Comment(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_newsname')
    text = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)
    moderation = models.BooleanField(default=True)

    def __str__(self):
        return self.text

news/forms.py
from django import forms
from django.forms import ModelForm
from .models import Comment, Article


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

class PostForm(ModelForm):
    class Meta:
        model = Article
        fields = ['picture', 'headline', 'content']

news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.views.generic.edit import DeleteView
from django.http import HttpResponseRedirect
from .models import Article
from django.views.generic.dates import YearArchiveView, MonthArchiveView, DayArchiveView
from django.urls import reverse
from .forms import CommentForm, PostForm
from django.utils import timezone
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin


class IndexView(generic.ListView):
    context_object_name = 'article_list'
    paginate_by = 5

    def get_queryset(self):
        """Return the last five published questions."""
        return Article.objects.order_by('-pub_date')[:5]

@login_required(login_url='/accounts/login')
def post_login(request, slug):
    post = get_object_or_404(Article, slug=slug)
    if request.method == 'POST':
        post = get_object_or_404(Article, id=request.POST.get('post_id'))
        return HttpResponseRedirect(post.get_absolute_url())
    else:
        return HttpResponseRedirect(post.get_absolute_url())


@login_required(login_url='/accounts/login')
@permission_required('news.add_article', raise_exception=True)
def add_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)

            post.reporter = request.user
            post.pub_date = timezone.now()
            post.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostForm()
    return render(request, 'news/news_add.html', {'form': form})


@login_required(login_url='/accounts/login')
@permission_required('news.edit_article', raise_exception=True)
def edit_post(request, slug):
    post = get_object_or_404(Article, slug=slug)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.reporter = request.user
            post.pub_date = timezone.now()
            post.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostForm(instance=post)
    return render(request, 'news/article_edit.html', {'form': form, 'post': post})


class PostDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'news.delete_article'
    model = Article
    success_url = reverse_lazy('news:index')



class DetailView(FormMixin, generic.DetailView):
    model = Article
    form_class = CommentForm

    def get_success_url(self):
        return reverse('news:detail', kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm(initial={'article': self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.name = self.request.user
        obj.article = Article.objects.get(slug=self.kwargs['slug'])
        form.save()
        return super(DetailView, self).form_valid(form)

class ArticleYearArchiveView(YearArchiveView):
    queryset = Article.objects.all()
    date_field = "pub_date"
    make_object_list = True
    allow_future = True

class ArticleMonthArchiveView(MonthArchiveView):
    queryset = Article.objects.all()
    date_field = "pub_date"
    allow_future = True

news/templates/news/article_archive_month.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        {% for article in object_list %}
            <li>{{ article.pub_date|date:"F j, Y" }}: {{ article.headline }}</li>
        {% endfor %}
    </ul>
    <p>
        {% if previous_month %}
            Previous Month: {{ previous_month|date:"F Y" }}
        {% endif %}
        {% if next_month %}
            Next Month: {{ next_month|date:"F Y" }}
        {% endif %}
</p>
</body>
</html>

news/templates/news/article_archive_year.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        {% for date in date_list %}
            <li>{{ date|date }}</li>
        {% endfor %}
    </ul>
    <div>
        <h1>All Articles for {{ year|date:"Y" }}</h1>
            {% for obj in object_list %}
            <p>
                {{ obj.headline }} - {{ obj.pub_date|date:"F j, Y" }}
            </p>
            {% endfor %}
</div>
</body>
</html>

news/templates/news/article_detail.html
{% extends "./news_base.html" %}
{% load static %}
{% block title %}{{ article.headline }}{% endblock %}


{% if perms.news and request.user == article.reporter %}
    {% block add_details %}
        <a href="{% url 'news:post-delete' article.slug%}">
            <img class="post-icons" src="{% static 'news/delete.png' %}">
        </a>  
        <a href="{% url 'news:edit_post' article.slug%}">
            <img class="post-icons" src="{% static 'news/edit.png' %}">
        </a>
    {% endblock %}
{% endif %}

{% block news_detail %}
    <div class="post-detail">
        <div class="header">
            <h1 class="post-title">{{ article.headline }}
            </h1>
            <div class="post-info">
                <span class="gap"></span>
                <span class="post-span">{{ article.reporter }}</span>
                <div id="meta-post">
                    <p>{{article.pub_date}}</p>
                    <hr>
                </div>           
            </div>
        </div>
        <img src="{{ article.picture.url }}">

        {{ article.content |safe }}

        
        <div class="comments">
            <h1 class="total-comments">{{article.comment_set.all.count}} Comment{{ article.comment_set.all.count| pluralize }}</h1>
            <hr>
            {% for comment in article.comment_set.all %}
                {% if comment.moderation %}
                    <p>{{ comment.text|safe }}</p>
                    <span class="gap"></span>
                    <span class="name">{{ comment.name }}</span>
                    <span class="date">({{comment.created_date}})</span>
                    <hr>
                {% endif %}
            {% endfor %}
        </div>


        <div class="add_comment">
            <h1 class="total-comments">Add a comment</h1>
            {% if request.user.is_authenticated %}
                
                <form action="" method="post">
                <fieldset class="module">
                    {% csrf_token %}
                    {{ form.non_field_errors }}                
                    <div>
                        {{ form.text.errors }}
                        <label for="{{ form.text.id_for_label }}">Comment:</label>
                        {{ form.text }}
                    </div>
                </fieldset>
                    <input class="default" type="submit" value="Submit">
                </form>
            {% else %}
                <div style="padding-top: 10px;"></div>
                <div class="alert alert-warning" role="alert">
                    <form action="{% url 'news:post_login' article.slug%}" method="post">
                        {% csrf_token %}
                    You must be <button type="submit" class="btn btn-link" style="padding: 0px; padding-bottom: 5px;">logged in</button> to comment.
                    </form>
                </div>
            {% endif %}
            <hr>
        </div>
    </div>


    <div style="clear: both;"></div>
    
{% endblock news_detail %}

news/templates/news/article_edit.html
{% extends "base.html" %}
{% block title %}Edit article{% endblock %}


{% block content %}

<!-- Content -->
<div id="content">
{% if request.user.is_authenticated and request.user == post.reporter %}
    <h1>Edit article</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        {% if form.errors %}
            <p class="errornote">Please correct the error below.</p>
        {% endif %}

		<fieldset class="module">
            {{ form.non_field_errors }}
            <div class="form-rows">
                {{ form.picture.errors }}
                <label for="{{ form.picture.id_for_label }}">Thumbnail:</label>
                <p>
                {{ form.picture }}</p>
            </div>

            <div class="form-rows">
                {{ form.headline.errors }}
                <label for="{{ form.headline.id_for_label }}">Headline:</label>
                {{ form.headline }}
            </div>

            <div class="form-rows">
                {{ form.content.errors }}
                <label for="{{ form.content.id_for_label }}">Content:</label>
                {{ form.content }}
            </div>


        </fieldset>
            <div class="submit-row">
                <input type="submit" value="Save" class="default">
            </div>
    </form>

{% else %}
<p class="errornote">Unauthorized access.</p>
<p>Oops! Only authors have access to edit their posts.</p>
{% endif %}

</div>

{% endblock %}

news/templates/news/article_list.html
{% extends "./news_base.html" %}
{% block title %}news{% endblock %}

{% block news_list %}
	<div class="popular-posts">
	    <div class="title" style="margin-left: 15px;">
	        <h2><span class="gap"></span>News</h2>
	        <span class="title-span"></span>
	    </div>
		{% for article in page_obj %}
			<div class="recent-posts">
	            <div class="post-outer">
	                <div class="post">
	                    <div class="container-fluid">
	                    <div class="row">
	                            <div  class="col-md-5">
	                                <div class="block-image">
	                                    <div class="thumb">
	                                        <a href="{% url 'news:detail' article.slug %}">
	                                            <img src="{{ article.picture.url }}">
	                                        </a>
	                                    </div>
	                                </div>
	                            </div>
	                            <div class="col-md-7">
	                                <div class="post-header">
	                                </div>
	                                <article>
	                                    <font class="retitle">
	                                        <h2>
	                                            <a href="{% url 'news:detail' article.slug %}"> {{article.headline}}</a>
	                                        </h2>
	                                    </font>
	                                    <div class="date-header">
	                                        <div id="meta-post">
	                                            <p>{{ article.pub_date }} - {{article.author}}</p>
	                                        </div>
	                                        <div class="resumo">
	                                            <span>{{ article.content| truncatewords:20 |safe }}</span>
	                                            <br>
	                                            <a class="read-more" href="{% url 'news:detail' article.slug %}">Read More</a>
	                                        </div>
	                                        <div style="clear: both;"></div>
	                                    </div>
	                                </article>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	            </div>
			</div> 
		{% endfor %}
	</div>

	<div id="pagination">
	    <span class="current">
	        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
	    </span>
	    <ul class="pagination">
	        {% if page_obj.has_previous %}
	            <li class="page-item">
	                <a class="page-link" aria-label="Previous" href="?page={{ page_obj.previous_page_number }}">
	                <span aria-hidden="true">&laquo;</span>
	                <span class="sr-only">Previous</span>
	                </a>
	            </li>
	        {% endif %}
	        
	        {% for x in paginator.page_range %}
	            <li class="page-item"><a class="page-link" href="?page={{ x }}">{{ x }}</a></li>
	        {% endfor %}

	        {% if page_obj.has_next %}
	            <li class="page-item">
	                <a class="page-link" aria-label="Next" href="?page={{ page_obj.next_page_number }}">
	                <span aria-hidden="true">&raquo;</span>
	                <span class="sr-only">Next</span>
	                </a>
	            </li>
	        {% endif %}
	    </ul>
	</div>	
{% endblock news_list %}  

news/templates/news/news_add.html
{% extends "base.html" %}
{% block title %}Add news{% endblock %}


{% block content %}

<!-- Content -->
<div id="content">
{% if perms.news %}
    <h1>Make a report</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {% if form.errors %}
            <p class="errornote">Please correct the error below.</p>
        {% endif %}

		<fieldset class="module">
            {{ form.non_field_errors }}
            <div class="form-rows">
                {{ form.picture.errors }}
                <label for="{{ form.picture.id_for_label }}">Thumbnail:</label>
                <p>
                {{ form.picture }}</p>
            </div>

            <div class="form-rows">
                {{ form.headline.errors }}
                <label for="{{ form.headline.id_for_label }}">Headline:</label>
                {{ form.headline }}
            </div>

            <div class="form-rows">
                {{ form.content.errors }}
                <label for="{{ form.content.id_for_label }}">Content:</label>
                {{ form.content }}
            </div>


        </fieldset>
            <div class="submit-row">
                <input type="submit" value="Save" class="default">
            </div>
    </form>

{% else %}
<p class="errornote">Unauthorized Access.</p>
<p>Oops! Only users with accounts have access to create posts. <a class="nav-link" href="{% url 'signup'%}">Create your account now.</a></p>
{% endif %}
</div>



{% endblock %}

news/templates/news/news_base.html
{% extends "base.html" %}
{% load static %}
{% block header %}

<div class="header-div">
	<h1>News
		{% if perms.news and request.user.is_authenticated %}
            <span class="post-span">
                <a href="{% url 'news:add_post' %}">
                    <img class="post-icons" src="{% static 'blog/add.png' %}">
                </a>  
                {% block add_details %}
            	{% endblock %}
            </span>
        {% endif %}
	</h1>
</div>

{% endblock %}

{% block content %}
<div class="container">

	{% block news_detail %}

	{% endblock news_detail %}

	{% block news_list %}

	{% endblock news_list %}
	
</div>


{% endblock content%}