FountainHub/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('news/', include('news.urls')),
    path('event/', include('event.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='index'),

    # CATEGORIES LINKS - Shows posts by categories
    # Shows all posts under campus
    path('campus/', views.campus_post, name='campus'),
    path('career/', views.career_post, name='career'),
    path('interview/', views.interview_post, name='interview'),
    path('others/', views.others_post, name='others'),
    path('islam/', views.islam_post, name='islam'),
    path('tutorial/', views.tutorial_post, name='tutorial'),

    # Full url would be something like; domainname.com/blog/add
    path('add/', views.add_post, name='add_post'),


    path('<slug:slug>/edit/', views.edit_post, name='edit_post'),

    path('<slug:slug>/delete/', views.PostDelete.as_view(), name='post-delete'),

    path('<slug:slug>/login/', views.post_login, name='post_login'),

    path('<slug:slug>/like/', views.like_post, name='like_post'),

    path('<slug:slug>/', views.post_detail, name='details'),






    #path('archive/<int:year>/<str:month>/', views.EventMonthArchiveView.as_view(), name="archive_month"),

    #path('archive/<int:year>/', views.EventYearArchiveView.as_view(), name="article_year_archive"),
]

blog/models.py
from django.contrib.auth.models import User
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone
from django.urls import reverse
from .managers import PostManager
from django.db import models


class Post(models.Model):
    CATEGORY_CHOICES = (
        ('Career', 'Career'),
        ('Campus', 'Campus'),
        ('Others', 'Others'),
        ('Tutorials', 'Tutorials'),
        ('Islam', 'Islam'),
        ('Interviews', 'Interviews'),
    )

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    thumbnail = models.ImageField(blank=True)
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES, default='others')
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(default='', blank=True, unique=True)
    text = RichTextUploadingField()
    likes = models.ManyToManyField(User, blank=True, related_name='likes')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    objects = PostManager()

    class Meta:
        ordering = ['-published_date']

    def save(self):
        self.published_date = timezone.now()
        self.slug = slugify(self.title)
        super(Post, self).save()

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('blog:details', kwargs={'slug': self.slug})


class Comment(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_blogname')
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_date = models.DateField(default=timezone.now)
    moderation = models.BooleanField(default=True)

    def __str__(self):
        return self.text

blog/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['thumbnail', 'category', 'title', 'text']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from . models import Post, Comment
from django.views.generic.dates import YearArchiveView, MonthArchiveView, WeekArchiveView
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import CommentForm, PostForm
from django.utils import timezone
from django.urls import reverse_lazy
from django.db.models import Count
import random
from django.core.paginator import Paginator



def post_list(request):

    latest_posts_list = Post.objects.order_by('-published_date')[:5]
    popular_posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-num_likes')[:5]
    first_career = Post.objects.get_category_posts('Career').annotate(num_likes=Count('likes'))[:1]
    career_list = Post.objects.get_category_posts('Career').annotate(num_likes=Count('likes'))[1:5]
    first_campus = Post.objects.get_category_posts('Campus').annotate(num_likes=Count('likes'))[:1]
    campus_list = Post.objects.get_category_posts('Campus').annotate(num_likes=Count('likes'))[1:5]
    first_islam = Post.objects.get_category_posts('Islam').annotate(num_likes=Count('likes'))[:1]
    islam_list = Post.objects.get_category_posts('Islam').annotate(num_likes=Count('likes'))[1:5]
    prof_interviews_list = Post.objects.get_category_posts('Interviews').annotate(num_likes=Count('likes'))[:3]
    tuts_guides_list = Post.objects.get_category_posts('Tutorials').annotate(num_likes=Count('likes'))[:3]
    others_list = Post.objects.get_category_posts('Others').order_by('-published_date')[:5]
    random_posts = random.sample(list(Post.objects.all()), 5)



    context = {
        'latest_posts_list': latest_posts_list,
        'popular_posts': popular_posts,
        'first_career': first_career,
        'career_list': career_list,
        'first_islam': first_islam,
        'islam_list': islam_list,
        'prof_interviews_list': prof_interviews_list,
        'tuts_guides_list': tuts_guides_list,
        'others_list': others_list,
        'first_campus': first_campus,
        'campus_list': campus_list,
        'random_posts': random_posts,
    }

    return render(request, 'blog/post_list.html', context)


def post_detail(request, slug):
    random_posts = random.sample(list(Post.objects.all()), 5)
    popular_posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-num_likes')[:5]
    post = get_object_or_404(Post, slug=slug)
    comments = Comment.objects.filter(post=post)
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.name = request.user
            comment.post = post
            comment.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()

    context = {
        'popular_posts': popular_posts,
        'Post': Post,
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
        'random_posts': random_posts,
    }
    return render(request, 'blog/post_detail.html', context)


def career_post(request):
    category = 'Career'
    category_list = Post.objects.get_category_posts('Career').order_by('-published_date')
    random_posts = random.sample(list(Post.objects.all()), 5)
    popular_posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-num_likes')[:5]


    paginator = Paginator(category_list, 4)
    page = request.GET.get('page')
    group = paginator.get_page(page)

    context = {
    'popular_posts': popular_posts,
    'random_posts': random_posts,
    'category_list': category_list,
    'category': category,
    'group': group,
    }
    return render(request, 'blog/category_list.html', context)


def campus_post(request):
    category = 'Campus'
    category_list = Post.objects.get_category_posts('Campus').order_by('-published_date')
    random_posts = random.sample(list(Post.objects.all()), 5)
    popular_posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-num_likes')[:5]

    paginator = Paginator(category_list, 4)
    page = request.GET.get('page')
    group = paginator.get_page(page)

    context = {
    'popular_posts': popular_posts,
    'random_posts': random_posts,
    'category_list': category_list,
    'category': category,
    'group': group,
    }
    return render(request, 'blog/category_list.html', context)


def islam_post(request):
    category = 'Islam'
    category_list = Post.objects.get_category_posts('Islam').order_by('-published_date')
    random_posts = random.sample(list(Post.objects.all()), 5)
    popular_posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-num_likes')[:5]

    paginator = Paginator(category_list, 2)
    page = request.GET.get('page')
    group = paginator.get_page(page)


    context = {
    'popular_posts': popular_posts,
    'random_posts': random_posts,
    'category_list': category_list,
    'category': category,
    'group': group,
    }
    return render(request, 'blog/category_list.html', context)


def interview_post(request):
    category = 'Interviews'
    category_list = Post.objects.get_category_posts('Interviews').order_by('-published_date')
    random_posts = random.sample(list(Post.objects.all()), 5)
    popular_posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-num_likes')[:5]

    
    paginator = Paginator(category_list, 2)
    page = request.GET.get('page')
    group = paginator.get_page(page)


    context = {
    'popular_posts': popular_posts,
    'random_posts': random_posts,
    'category_list': category_list,
    'category': category,
    'group': group,
    }
    return render(request, 'blog/category_list.html', context)


def tutorial_post(request):
    category = 'Tutorials'
    category_list = Post.objects.get_category_posts('Tutorials').order_by('-published_date')
    random_posts = random.sample(list(Post.objects.all()), 5)
    popular_posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-num_likes')[:5]

    
    paginator = Paginator(category_list, 2)
    page = request.GET.get('page')
    group = paginator.get_page(page)

    context = {
    'popular_posts': popular_posts,
    'random_posts': random_posts,
    'category_list': category_list,
    'category': category,
    'group': group,
    }
    return render(request, 'blog/category_list.html', context)


def others_post(request):
    category = 'Others'
    category_list = Post.objects.get_category_posts('Others').order_by('-published_date')
    random_posts = random.sample(list(Post.objects.all()), 5)
    popular_posts = Post.objects.annotate(num_likes=Count('likes')).order_by('-num_likes')[:5]

    paginator = Paginator(category_list, 2)
    page = request.GET.get('page')
    group = paginator.get_page(page)

    context = {
    'popular_posts': popular_posts,
    'random_posts': random_posts,
    'category_list': category_list,
    'category': category,
    'group': group,
    }
    return render(request, 'blog/category_list.html', context)


@login_required(login_url='/accounts/login')
def post_login(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        post = get_object_or_404(Post, id=request.POST.get('post_id'))
        return HttpResponseRedirect(post.get_absolute_url())
    else:
        return HttpResponseRedirect(post.get_absolute_url())



@login_required(login_url='/accounts/login')
def like_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        post = get_object_or_404(Post, id=request.POST.get('post_id'))
        is_liked = False
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            is_liked = False
        else:
            post.likes.add(request.user)
            is_liked = True
        return HttpResponseRedirect(post.get_absolute_url())
    else:
        return HttpResponseRedirect(post.get_absolute_url())


@login_required(login_url='/accounts/login')
def add_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)

            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostForm()
    return render(request, 'blog/post_add.html', {'form': form})


@login_required(login_url='/accounts/login')
def edit_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form, 'post': post})


        

class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')


class PostYearArchiveView(YearArchiveView):
    queryset = Post.objects.all()
    date_field = "pub_date"
    make_object_list = True
    allow_future = True


class PostMonthArchiveView(MonthArchiveView):
    queryset = Post.objects.all()
    date_field = "pub_date"
    allow_future = True


class PostWeekArchiveView(WeekArchiveView):
    queryset = Post.objects.all()
    date_field = "pub_date"
    week_format = "%W"
    allow_future = True

blog/templates/blog/base_blog.html
{% extends "base.html" %}
{% load static %}
{% block header %}

<div class="header-div">
	<h1>Blog
		{% if request.user.is_authenticated %}
            <span class="post-span">
                <a href="{% url 'blog:add_post' %}">
                    <img class="post-icons" src="{% static 'blog/add.png' %}">
                </a>  
            </span>
        {% endif %}
	</h1>

</div>

{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-8">
			<!-- FOR THE INDEX PAGE OF THE BLOG -->
			{% block post_list %}

			{% endblock post_list %}
			<!-- END OF THE INDEX PAGE OF THE BLOG -->

			<!-- DETAIL PAGE OF BLOG -->
			{% block post_detail %}

			{% endblock post_detail %}
			<!-- END OF DETAIL PAGE OF BLOG -->

			<!--CATEGORY LISTS--->
			{% block category_posts %}

			{% endblock category_posts %}
			<!-- END OF CATEGORY LISTS--->
		</div>
		<div class="col-lg-4">

			<!-- POPULAR POSTS-->
			{% block popular_posts %}

			{% endblock popular_posts %}
			<!-- END OF POPULAR POSTS-->


			<!-- CATEGORIES -->
				<div class="popular-posts">
        			<div class="title">
            			<h2><span class="gap"></span>Categories</h2>
            			<span class="title-span"></span>
        			</div>
        		</div>
				<ul class="list-group">
					<li class="list-group-item"><a href="/blog/career">Career</a></li>
					<li class="list-group-item"><a href="/blog/campus">Campus</a></li>
					<li class="list-group-item"><a href="/blog/islam">Islam</a></li>
					<li class="list-group-item"><a href="/blog/tutorial/">Tutorials</a></li>
					<li class="list-group-item"><a href="/blog/interview/">Interviews</a></li>
					<li class="list-group-item"><a href="/blog/others/">Others</a></li>
				</ul>
			<!-- END CATEGORIES -->

			<!--OTHERS POST-->
			{% block random_posts %}

			{% endblock random_posts %}
			<!--END OF OTHERS POSTS-->

			<!-- END OF CONSTANT BETWEEN INDEX AND DETAIL -->
		</div>
	</div>
</div>
{% endblock content%}

blog/templates/blog/blog_base.html
{% extends "base.html" %}
{% load static %}
{% block header %}

<div class="header-div">
	<h1>Blog
		{% if request.user.is_authenticated %}
            <span class="post-span">
            	<a href="{% url 'blog:add_post' %}">
                    <img class="post-icons" src="{% static 'blog/add.png' %}">
                </a>  
            	{% block add_details %}
            	{% endblock %}
                
            </span>
        {% endif %}
	</h1>

</div>

{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-8">
			<!-- FOR THE INDEX PAGE OF THE BLOG -->
			{% block post_list %}

			{% endblock post_list %}
			<!-- END OF THE INDEX PAGE OF THE BLOG -->

			<!-- DETAIL PAGE OF BLOG -->
			{% block post_detail %}

			{% endblock post_detail %}
			<!-- END OF DETAIL PAGE OF BLOG -->

			<!--CATEGORY LISTS--->
			{% block category_posts %}

			{% endblock category_posts %}
			<!-- END OF CATEGORY LISTS--->
		</div>
		<div class="col-lg-4">

			<!-- POPULAR POSTS-->
			{% block popular_posts %}

			{% endblock popular_posts %}
			<!-- END OF POPULAR POSTS-->


			<!-- CATEGORIES -->
				<div class="popular-posts">
        			<div class="title">
            			<h2><span class="gap"></span>Categories</h2>
            			<span class="title-span"></span>
        			</div>
        		</div>
				<ul class="list-group">
					<li class="list-group-item"><a href="/blog/career">Career</a></li>
					<li class="list-group-item"><a href="/blog/campus">Campus</a></li>
					<li class="list-group-item"><a href="/blog/islam">Islam</a></li>
					<li class="list-group-item"><a href="/blog/tutorial/">Tutorials</a></li>
					<li class="list-group-item"><a href="/blog/interview/">Interviews</a></li>
					<li class="list-group-item"><a href="/blog/others/">Others</a></li>
				</ul>
			<!-- END CATEGORIES -->

			<!--OTHERS POST-->
			{% block random_posts %}

			{% endblock random_posts %}
			<!--END OF OTHERS POSTS-->

			<!-- END OF CONSTANT BETWEEN INDEX AND DETAIL -->
		</div>
	</div>
</div>
{% endblock content%}

blog/templates/blog/post_add.html
{% extends "base.html" %}
{% block title %}Add post{% endblock %}


{% block content %}

<!-- Content -->
<div id="content">
{% if request.user.is_authenticated %}
    <h1>Add post</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {% if form.errors %}
            <p class="errornote">Please correct the error below.</p>
        {% endif %}

		<fieldset class="module">
            {{ form.non_field_errors }}
            <div class="form-rows">
                {{ form.thumbnail.errors }}
                <label for="{{ form.thumbnail.id_for_label }}">Thumbnail:</label>
                <p>
                {{ form.thumbnail }}</p>
            </div>

            <div class="form-rows">
                {{ form.category.errors }}
                <label for="{{ form.category.id_for_label }}">Category:</label>
                {{ form.category }}
            </div>

            <div class="form-rows">
                {{ form.title.errors }}
                <label for="{{ form.title.id_for_label }}">Title:</label>
                {{ form.title }}
            </div>

            <div class="form-rows">
                {{ form.text.errors }}
                <label for="{{ form.text.id_for_label }}">Text:</label>
                {{ form.text }}
            </div>

        </fieldset>
            <div class="submit-row">
                <input type="submit" value="Save" class="default">
            </div>
    </form>

{% else %}
<p class="errornote">Unauthorized Access.</p>
<p>Oops! Only users with accounts have access to create posts. <a class="nav-link" href="{% url 'signup'%}">Create your account now.</a></p>
{% endif %}
</div>



{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% load staticfiles %}
{% block content %}
    {% if request.user.is_authenticated and request.user == post.author %}
    <div class="container">
        <div class="delete-margin">
            <h1 class="password-header">Are you sure?</h1>
            <p>Are you sure you want to delete this blog post? All of the likes and comments would be deleted alongside it.</p>
            <form action="{% url 'blog:post-delete' post.slug %}" method="post">
                {%csrf_token%}
                <input class="default-delete" type="submit" value="Yes i'm sure.">
            </form>
            <form action="{% url 'blog:details' post.slug %}" method="post">
                {%csrf_token %}
                <input class="cancel-link" type="submit" value="No, take me back">
            </form>
        </div>
    </div>
    {% endif %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "./blog_base.html" %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}

{% if request.user.is_authenticated and request.user == post.author %}
    {% block add_details %}
        <a href="{% url 'blog:post-delete' post.slug%}">
            <img class="post-icons" src="{% static 'blog/delete.png' %}">
        </a>  
        <a href="{% url 'blog:edit_post' post.slug%}">
            <img class="post-icons" src="{% static 'blog/edit.png' %}">
        </a>
    {% endblock %}
{% endif %}



{% block post_detail %}
    <div class="post-detail">
        <div class="header">
            <h1 class="post-title">{{ post.title }}
            </h1>
            <div class="post-info">
                <span class="gap"></span>
                <span class="post-span">{{ post.author }}</span>
                <span class="gap"></span>
                <span class="post-span">{{post.category}}</span>
                <span class="gap"></span>
                <span class="post-span">{{ total_likes }} Like{{ total_likes| pluralize }}</span>


                <div id="meta-post">
                    <p>{{post.published_date}}</p>
                    <hr>
                </div>           
            </div>
        </div>
        <img src="{{ post.thumbnail.url }}" alt="Logo">


        {{ post.text |safe }}


        <div class="comment_form">
            <span class="gap"></span>
            <span class="post-span">{{ total_likes }} Like{{ total_likes| pluralize }}</span>
            {% if request.user.is_authenticated %}
                <form action="{% url 'blog:like_post' post.slug%}" method="post" style="padding-top: 10px;">
                    {% csrf_token %}
                    {% if is_liked %}
                        <button class="btn btn-danger" type="submit" name="post_id" value="{{ post.id }}">Dislike</span></button>
                    {% else %}
                        <button class="btn btn-success" type="submit" name="post_id" value="{{ post.id }}">Like</button>
                    {% endif %}
                </form>
                <hr>
                
            {% else %}
                <div style="padding-top: 10px;"></div>
                <div class="alert alert-warning" role="alert">
                    <form action="{% url 'blog:post_login' post.slug%}" method="post">
                        {% csrf_token %}
                    You must be <button type="submit" class="btn btn-link" style="padding: 0px; padding-bottom: 5px;">logged in</button> to comment or like a post.
                    </form>
                </div>
                {% endif %}
        </div>
        <div class="comments">
            <h1 class="total-comments">{{comments.count}} Comment{{ comments.count| pluralize }}</h1>
            {% for comment in comments %}
                {% if comment.moderation %}
                    <p>{{ comment.text|safe }}</p>
                    <span class="gap"></span>
                    <span class="name">{{ comment.name }}</span>
                    <span class="date">({{comment.created_date}})</span>
                    <hr>
                {% endif %}
            {% endfor %}
        </div>

        {% if request.user.is_authenticated %}
        <div class="add_comment">
            <h1 class="total-comments">Add a comment</h1>
            <form action="" method="post">
                    <fieldset class="module">
                        {% csrf_token %}
                        {{ comment_form.non_field_errors }}                
                        <div>
                            {{ commemnt_form.text.errors }}
                            <label for="{{ form.text.id_for_label }}">Comment:</label>
                            {{ comment_form.text }}
                        </div>
                    </fieldset>
                        <input class="default" type="submit" value="Submit">
                    </form>
        </div>
        {% endif %}
    </div>
{% endblock post_detail %}


<!-- POPULAR POSTS -->
{% block popular_posts %}
    <div class="popular-posts">
        <div class="title">
            <h2><span class="gap"></span>Popular Posts</h2>
            <span class="title-span"></span>
        </div>
        <div class="content">
            <ul>
                {% for post in popular_posts %}
                    <li>
                        <div class="item-content">
                            <div class="item-thumbnail">
                                <a href="{% url 'blog:details' post.slug %}">
                                    <img src="{{ post.thumbnail.url }}" class="item-thumb" width="72", height="72", border="0">
                                </a>
                            </div>
                            <div class="item-title">
                                <a class="item-link" href="{% url 'blog:details' post.slug %}">{{post.title}}</a>
                            </div>
                            <div id="meta-post">
                                <p>{{post.category}} - {{post.author}}</p>
                            </div>
                        </div>
                        <div style="clear: both;"></div>
                    </li>

                {% endfor %}
            </ul>
        </div>  
    </div>
{% endblock popular_posts %}
<!-- END POPULAR POSTS -->

<!-- RANDOM POSTS-->
{% block random_posts %}
    <div class="popular-posts">
        <div class="title">
            <h2><span class="gap"></span>Random Posts</h2>
            <span class="title-span"></span>
        </div>
        <div class="content">
            <ul>
                {% for post in random_posts %}
                    <li>
                        <div class="item-content">
                            <div class="item-thumbnail">
                                <a href="{% url 'blog:details' post.slug %}">
                                    <img src="{{ post.thumbnail.url }}" class="item-thumb" width="72", height="72", border="0">
                                </a>
                            </div>
                            <div class="item-title">
                                <a class="item-link" href="{% url 'blog:details' post.slug %}">{{post.title}}</a>
                            </div>
                            <div id="meta-post">
                                <p>{{post.published_date}}</p>
                            </div>
                        </div>
                        <div style="clear: both;"></div>
                    </li>

                {% endfor %}
            </ul>
        </div>  
    </div>
{% endblock random_posts %}
<!--END OF RANDOM POSTS-->

blog/templates/blog/post_edit.html
{% extends "base.html" %}
{% block title %}Edit post{% endblock %}


{% block content %}

<!-- Content -->
<div id="content">
{% if request.user.is_authenticated and request.user == post.author %}
    <h1>Edit post</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        {% if form.errors %}
            <p class="errornote">Please correct the error below.</p>
        {% endif %}

		<fieldset class="module">
            {{ form.non_field_errors }}
            <div class="form-rows">
                {{ form.thumbnail.errors }}
                <label for="{{ form.thumbnail.id_for_label }}">Thumbnail:</label>
                <p>
                {{ form.thumbnail }}</p>
            </div>

            <div class="form-rows">
                {{ form.category.errors }}
                <label for="{{ form.category.id_for_label }}">Category:</label>
                {{ form.category }}
            </div>

            <div class="form-rows">
                {{ form.title.errors }}
                <label for="{{ form.title.id_for_label }}">Title:</label>
                {{ form.title }}
            </div>

            <div class="form-rows">
                {{ form.text.errors }}
                <label for="{{ form.text.id_for_label }}">Text:</label>
                {{ form.text }}
            </div>

        </fieldset>
            <div class="submit-row">
                <input type="submit" value="Save" class="default">
            </div>
    </form>

{% else %}
<p class="errornote">Unauthorized access.</p>
<p>Oops! Only authors have access to edit their posts.</p>
{% endif %}

</div>

{% endblock %}